mixmicro:
  boot:
    logging:
      admin:
        server-address: user:123456@127.0.0.1:9090
      format-console-log-json: true
      report-number-of-request-log: 2
      report-interval-second: 10